config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'dashboard', to: 'dashboard#index'

  resources :departments

  get 'signup', to: 'employees#new'
  resources :employees, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :cost_centers

  resources :tasks

  resources :work_times
end

app/models/work_time.rb
class WorkTime < ActiveRecord::Base
  belongs_to :employee
  belongs_to :task

  validate :check_dates

  def check_dates
    errors.add(:base, "End date should be greater than start") if self.datetime_start >= self.datetime_end
  end
end

app/controllers/work_times_controller.rb
class WorkTimesController < ApplicationController
  before_action :require_authentication, only: [:index, :new, :create, :show, :edit]
  before_action :set_work_time, only: [:show, :edit, :update]

  def index
    @work_times = WorkTime.all
  end

  def new
    @work_time = WorkTime.new
  end

  def create
    @work_time = WorkTime.new(work_time_params)
    if @work_time.save
      redirect_to work_times_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @work_time.update(work_time_params)
      flash[:success] = "WorkTime successfully updated!"
      redirect_to work_time_path(@work_time)
    else
      render 'edit'
    end
  end

  private
    def work_time_params
      params.require(:work_time).permit(:description, :datetime_start, :datetime_end, :employee_id, :task_id)
    end

    def set_work_time
      @work_time = WorkTime.find(params[:id])
    end
end

app/views/work_times/_form.html.erb
<%= render 'shared/errors', obj: @work_time %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@work_time, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %><br>
        </div>
        <div class="col-sm-8">
            <%= f.text_area :description, class: "form-control", placeholder: "Descrição do que foi realizado", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :datetime_start %><br>
        </div>
        <div class="col-sm-8">
          <%= f.datetime_select :datetime_start %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :datetime_end %><br>
        </div>
        <div class="col-sm-8">
          <%= f.datetime_select :datetime_end %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :employee_id %><br>
        </div>
        <div class="col-sm-8">
          <%= f.collection_select(:employee_id, Employee.all, :id, :email) %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :task_id %><br>
        </div>
        <div class="col-sm-8">
          <%= f.collection_select(:task_id, Task.all, :id, :name) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>

    <div class="text-center">
      [ <%= link_to 'Cancelar inserção e voltar para a lista de departamentos', departments_path %> ]
    </div>
  </div>
</div>

app/views/work_times/edit.html.erb
<h1 class="text-center">Edite a hora trabalhada</h1>

<%= render 'form' %>

app/views/work_times/index.html.erb
<h1 class="text-center">Todas as horas trabalhadas</h1>
<p>
  <%= link_to 'Create a new work time', new_work_time_path %>
</p>

<% @work_times.each do |work_time| %>
  <ul class="listing">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
        <li>
          <%= link_to work_time.description, work_time_path(work_time) %>
        </li>
      </div>
      <div class="">
        <%= link_to 'Editar', edit_work_time_path(work_time), class: "btn btn-xs btn-primary" %>
        <%= link_to 'Deletar', work_time_path(work_time), method: :delete,
                                                            data: {confirm: "Você tem certeza?"},
                                                            class: "btn btn-xs btn-danger" %>
      </div>
    </div>
  </ul>
<% end %>

app/views/work_times/new.html.erb
<h1 class="text-center">Adicionar uma hora trabalhada</h1>

<%= render 'form' %>

app/views/work_times/show.html.erb
<h2 class="text-center">Descrição da worktime: <%= @work_time.description %></h2>