config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'dashboard', to: 'dashboard#index'

  resources :departments

  get 'signup', to: 'employees#new'
  resources :employees, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :cost_centers

  resources :tasks

  resources :work_times
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :employees
  validates :name, presence: true, length: {minimum: 3, maximum: 50}

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :require_authentication, only: [:index, :new, :create, :update, :show, :edit, :destroy]
  before_action :set_department, only: [:edit, :update, :show, :destroy]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:success] = "Departamento foi criado!"
      redirect_to department_path(@department)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      flash[:success] = "Departamento foi atualizado com sucesso!"
      redirect_to department_path(@department)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @department.destroy
    flash[:danger] = "Departments was successfully deleted!"
    redirect_to departments_path
  end


  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end

    def require_admin
      if !logged_as_admin?
        flash[:danger] = "Only administrators can perform this action!"
        redirect_to root_path
      end
    end

end

app/views/departments/_form.html.erb
<%= render 'shared/errors', obj: @department %>

<div class="row">
  <div class="col-xs-12">
  <%= form_for(@department, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %><br>
      </div>
      <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nome do departamento", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>

    <div class="text-center">
      [ <%= link_to 'Cancelar inserção e voltar para a lista de departamentos', departments_path %> ]
    </div>
  </div>
</div>

app/views/departments/edit.html.erb
<h1 class="text-center">Editar departamento existente</h1>

<%= render 'form' %>

app/views/departments/index.html.erb
<h1 class="text-center">Listando todos os departments</h1>
<p>
  <%= link_to 'Create a new department', new_department_path %>
</p>

<% @departments.each do |department| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="department-title">
          <%= link_to department.name, department_path(department) %>
        </div>
        <div class="department_actions">
          <% if logged_as_admin? %>
            <%= link_to 'Editar', edit_department_path(department), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Deletar', department_path(department), method: :delete,
                                                                data: {confirm: "Você tem certeza?"},
                                                                class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/departments/new.html.erb
<h1 class="text-center">Criar um departamento</h1>

<%= render 'form' %>

app/views/departments/show.html.erb
<h2 class="text-center">Nome: <%= @department.name %></h2>

<h3>Funcionários: </h3>
<% @department.employees.each do |employee| %>
  <p> <%= link_to employee.full_name, employee_path(employee) %></p>
<% end %>

<div class="department_actions">
  <% if logged_as_admin? %>
    <%= link_to 'Editar', edit_department_path(@department), class: "btn btn-xs btn-primary" %>
    <%= link_to 'Deletar', department_path(@department), method: :delete,
                                                          data: {confirm: "Você tem certeza?"},
                                                          class: "btn btn-xs btn-danger" %>
    <%= link_to 'Ver todos os departmentos', departments_path, class: "btn btn-xs btn-success" %>
  <% end %>
</div>