config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'dashboard', to: 'dashboard#index'

  resources :departments

  get 'signup', to: 'employees#new'
  resources :employees, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :cost_centers

  resources :tasks

  resources :work_times
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#">Victor Amorim</a>
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 ">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "PocWeb", root_path, class: "navbar-brand", id: "logo" %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toogle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Admin' if current_employee.admin? %></li>
          <li><%= link_to 'Tasks', tasks_path if current_employee.admin? %></li>
          <li><%= link_to 'Cost Centers', cost_centers_path %></li>
          <li><%= link_to 'Work Times', work_times_path %></li>
          <li><%= link_to 'Departamentos', departments_path %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <li><%= link_to 'Edit your profile', edit_employee_path(current_employee) %></li>
        <% else %>
          <li><%= link_to 'Sign up', signup_path %></li>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="<%= active_class(dashboard_path)%>"><%= link_to 'Dashboard', dashboard_path %></li>
        <li class="<%= active_class(work_times_path)%>"><%= link_to 'Controle de Horários', work_times_path %></li>
        <li class=""><a href="#">Diario</a></li>
        <li class="<%= active_class(cost_centers_path)%>"><%= link_to 'Centros de custo', cost_centers_path %></li>
        <li class=""><a href="#">Solicitações</a></li>
        <li class=""><a href="#">Painel Administrativo</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/sidebar' if logged_in? %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>